export const routes = {
  dashboard: "/dashboard",
  intake: "/intake",
  investigations: "/investigations",
  workspace: "/workspace",
  caseWorkspace: (caseId: string) => `/investigations/${caseId}`,
  debate: "/debate",
  debateFor: (caseId: string) => `/debate?caseId=${encodeURIComponent(caseId)}`,
  evidence: "/evidence",
  evidenceFor: (caseId: string) => `/evidence?caseId=${encodeURIComponent(caseId)}`,
  verification: "/verification",
  verificationFor: (caseId: string) => `/verification?caseId=${encodeURIComponent(caseId)}`,
  review: "/review",
  humanReview: "/review",
  auditLogs: "/audit-logs",
  auditLogsFor: (caseId: string) => `/audit-logs?caseId=${encodeURIComponent(caseId)}`,
  replay: "/replay",
  replayFor: (caseId: string) => `/replay?caseId=${encodeURIComponent(caseId)}`,
  reports: "/reports",
  reportsFor: (caseId: string) => `/reports?caseId=${encodeURIComponent(caseId)}`,
  analytics: "/analytics",
  evaluation: "/evaluation",
  knowledgeBase: "/knowledge-base",
  employeeTransactions: "/employee-transactions",
  settings: "/settings",
} as const;
