import type { ReportArtifact } from "@/types/domain";

/**
 * Client-side report downloads with zero extra dependencies.
 *
 * - JSON: real one-click file download via a Blob.
 * - PDF: opens a print-optimized window and triggers the browser's
 *   "Save as PDF" flow. This works in every modern browser without adding a
 *   PDF library or a backend endpoint.
 */

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Give the browser a tick to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function safeName(report: ReportArtifact) {
  return report.id.replace(/[^a-z0-9-_]+/gi, "-");
}

/** Download the full report object as a formatted .json file. */
export function downloadReportJson(report: ReportArtifact) {
  const blob = new Blob([JSON.stringify(report, null, 2)], {
    type: "application/json",
  });
  triggerDownload(blob, `${safeName(report)}.json`);
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function reportBody(report: ReportArtifact) {
  const sections = report.sections
    .map((section) => `<li>${escapeHtml(section)}</li>`)
    .join("");

  return `<section class="report">
  <h1>${escapeHtml(report.title)}</h1>
  <div class="meta">${escapeHtml(report.audience)} &middot; Updated ${escapeHtml(report.updatedAt || "n/a")}</div>
  <div>
    <span class="pill">Status: ${escapeHtml(report.status)}</span>
    <span class="pill">Risk: ${escapeHtml(report.riskVerdict)}</span>
    <span class="pill">Confidence: ${(report.confidence * 100).toFixed(0)}%</span>
  </div>

  <h2>Executive summary</h2>
  <p>${escapeHtml(report.executiveSummary)}</p>

  <h2>Decision</h2>
  <div class="grid">
    <div><strong>Human decision:</strong> ${escapeHtml(report.humanDecision)}</div>
    <div><strong>Reviewer signature:</strong> ${escapeHtml(report.reviewerSignature)}</div>
  </div>

  <h2>Sections</h2>
  <ul>${sections}</ul>

  <div class="footer">Generated by Skeptic Engine &middot; ${escapeHtml(report.id)}</div>
</section>`;
}

function printableDocument(title: string, bodies: string[]) {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #14213d; margin: 40px; line-height: 1.5; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  .meta { color: #6b7280; font-size: 12px; margin-bottom: 20px; }
  .pill { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; background: #eef2ff; color: #3730a3; margin-right: 6px; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; margin: 24px 0 6px; }
  p { margin: 0 0 8px; }
  ul { margin: 0; padding-left: 18px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 24px; font-size: 13px; }
  .footer { margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 10px; color: #9ca3af; font-size: 11px; }
  .report { page-break-after: always; }
  .report:last-child { page-break-after: auto; }
  @media print { body { margin: 24px; } }
</style>
</head>
<body>
  ${bodies.join("\n")}
  <script>window.onload = function () { window.print(); };</script>
</body>
</html>`;
}

function openPrintable(title: string, bodies: string[]): boolean {
  const win = window.open("", "_blank", "width=900,height=1000");
  if (!win) {
    return false;
  }
  win.document.open();
  win.document.write(printableDocument(title, bodies));
  win.document.close();
  return true;
}

/**
 * Open a print-ready report and invoke the browser print dialog so the user can
 * save it as a PDF. Returns false if the popup was blocked.
 */
export function downloadReportPdf(report: ReportArtifact): boolean {
  return openPrintable(report.title, [reportBody(report)]);
}

/** Open a single print-ready document containing every provided report. */
export function downloadReportsPdf(reports: ReportArtifact[]): boolean {
  if (reports.length === 0) {
    return false;
  }
  return openPrintable("Skeptic Engine reports", reports.map(reportBody));
}
